name: Terraform-S3-Static-Site-Hosting

on:
  push:
    branches:
      - main
      
jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Deploy to S3
        run: |
          aws s3 sync demo_static_site ${{secrets.BUCKET_URL}} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{secrets.CLOULDFRONT_DESTRIBUTION_ID}} --paths "/*"